inherit_from: config/default.yml

 # Style/StringLiterals:  
#   EnforcedStyle: double_quotes
#   Enabled: true
AllCops:
  RubyInterpreters:
    - ruby
    - macruby
    - rake
    - jruby
    - rbx
  Include:
    - 'Rakefile'
    - 'config.ru'
    - 'lib/**/*.rake'
    - '*.rb'
    - '**/*.rb'
    - '**/**/*.rb'
    - '**/**/**/*.rb'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'README.md'
    - 'Gemfile.lock'
    - 'node_modules/**/*'
    - 'config/**/*'
  UseCache: false
  CacheRootDirectory: false
